# Generated by Django 2.2.4 on 2020-10-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamRetakeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
