# Generated by Django 2.2.4 on 2020-10-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamRetakeApp', '0002_auto_20201021_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('quote', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteuploaded', to='ExamRetakeApp.User')),
                ('favoredquote', models.ManyToManyField(related_name='favoredaquote', to='ExamRetakeApp.User')),
            ],
        ),
    ]
