# Generated by Django 2.2.4 on 2020-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamRetakeApp', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoter',
            field=models.CharField(default='name', max_length=55),
        ),
    ]
